version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'auto-merge'
    open-pull-requests-limit: 10
    groups:
      radix-ui:
        patterns:
          - '@radix-ui/*'
      ai-sdk:
        patterns:
          - '@ai-sdk/*'
          - 'ai'
          - 'openai'
      eslint:
        patterns:
          - 'eslint*'
          - '@eslint/*'
      testing:
        patterns:
          - 'vitest'
          - '@vitest/*'
          - '@testing-library/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'auto-merge'
