export { getAIProvider } from './router';
export { trackAIAction } from './cost-tracker';
export { generateWithGemini } from './providers/gemini';
export type { AITask, InsightType, EntityType, GeneratedInsight, InsightInput, CostEntry } from './types';
export { generateInsights } from './agents/insight-engine';
export { detectStaleDeals } from './agents/stale-deal-detector';
export { detectBidMatches } from './agents/bid-matcher';
export { detectNextActions } from './agents/next-action-suggester';
export { draftEmail } from './agents/email-drafter';
export type { DraftType } from './agents/email-drafter';
export { buildDigest } from './agents/digest-builder';
export { detectBudgetAnomalies } from './agents/budget-anomaly';
export { executeNLQuery } from './agents/nl-query';
export { queryTools, executeToolCall } from './tools';
